services:
  front-end:
    hostname: front-end
    build: ./front-end
    ports:
      - "80:5000"
    environment:
      FLASK_RUN_PORT: 5000
      FLASK_DEBUG: 'True'
      USERS_URL: http://users:5000
      VOTES_URL: http://polls:5000

  postgres:
    image: bitnami/postgresql:16
    environment:
      POSTGRESQL_USERNAME: user
      POSTGRESQL_PASSWORD: 1234


