services:
  front-end:
    build: 
      context: ./front-end
      additional_contexts:
        protos: ./protos
    ports:
      - 80:5000
    environment:
      FLASK_RUN_PORT: 5000
      FLASK_DEBUG: "True"
      USERS_URL: http://users:5000
      POLLS_URL: http://polls:5000

  polls:
    build: 
      context: ./polls
      additional_contexts:
        protos: ./protos
    environment:
      USERS_URL: http://users:5000
      DB_USER: user
      DB_PASSWORD: 1234
      PORT: 5000

  users:
    build: 
      context: ./users
      additional_contexts:
        protos: ./protos
    environment:
      DB_USER: user
      DB_PASSWORD: 1234
      PORT: 5000

  postgres:
    image: bitnami/postgresql:16
    environment:
      POSTGRESQL_USERNAME: user
      POSTGRESQL_PASSWORD: 1234
