services:
  front-end:
    build: ./front-end
    environment:
      FLASK_RUN_PORT: 5000
      FLASK_DEBUG: "True"
      USERS_URL: users:5000
      POLLS_URL: polls:5000
    deploy:
      replicas: 2
    depends_on:
      - polls
      - users
    volumes:
      - type: bind
        source: ./front-end
        target: /app
      - type: bind
        source: ./protos
        target: /protos

  polls:
    build: ./polls
    command: watchmedo auto-restart --recursive --pattern="*.py" --directory="/app" python -- -m app
    environment:
      USERS_URL: users:5000
      DB_USER: user
      DB_PASSWORD: 1234
      DB_URL: postgres
      DB_DATABASE: database
      PORT: 5000
    deploy:
      replicas: 2
    volumes:
      - type: bind
        source: ./polls
        target: /app
      - type: bind
        source: ./protos
        target: /protos

  users:
    build: ./users
    command: watchmedo auto-restart --recursive --pattern="*.py" --directory="/app" python -- -m app
    environment:
      DB_USER: user
      DB_PASSWORD: 1234
      DB_URL: postgres
      DB_DATABASE: database

      PORT: 5000
    deploy:
      replicas: 2
    volumes:
      - type: bind
        source: ./users
        target: /app
      - type: bind
        source: ./protos
        target: /protos

  postgres:
    image: bitnami/postgresql:16
    environment:
      POSTGRESQL_USERNAME: user
      POSTGRESQL_PASSWORD: 1234
      POSTGRESQL_DATABASE: database

  nginx:
    build: ./nginx
    ports:
      - 5000:5000
    depends_on:
      - front-end
